tms/force-app/main/default/objects/TMS_Contact__c/TMS_Contact__c.object-meta.xml
<CustomObject>
    <label>TMS Contact</label>
    <nameField>
        <label>TMS Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TMS Contacts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/TMS_Contact__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

tms/force-app/main/default/objects/TMS_Contact__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

tms/force-app/main/default/classes/ContactController.cls
public with sharing class ContactController {
    @AuraEnabled
    public static List<TMS_Contact__c> findContacts(String firstName,String lastName,String email) {
        String fkey = '%' + firstName + '%';
        String lkey = '%' + lastName + '%';
        String emailkey = '%' + email + '%';
        return [
            SELECT Id, 	First_Name__c,Last_Name__c, Email_Address__c
            FROM TMS_Contact__c
            WHERE First_Name__c LIKE :fkey and Last_Name__c LIKE :lkey and Email_Address__c LIKE :emailkey
        ];
    }
}