tms/force-app/main/default/objects/TMS_Contact__c/TMS_Contact__c.object-meta.xml
<CustomObject>
    <label>TMS Contact</label>
    <nameField>
        <label>TMS Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TMS Contacts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/TMS_Contact__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

tms/force-app/main/default/objects/TMS_Contact__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

tms/force-app/main/default/objects/TMS_Ticket__c/TMS_Ticket__c.object-meta.xml
<CustomObject>
    <label>TMS Ticket</label>
    <nameField>
        <label>TMS Ticket Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TMS Tickets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TMS_Ticket__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <formula>TMS_Contact__r.First_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>First Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TMS_Ticket__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <formula>TMS_Contact__r.Last_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Last Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TMS_Ticket__c/fields/Severity__c.field-meta.xml
<CustomField>
    <fullName>Severity__c</fullName>
    <label>Severity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>S1</fullName>
            </value>
            <value>
                <fullName>S2</fullName>
            </value>
            <value>
                <fullName>S3</fullName>
            </value>
            <value>
                <fullName>S4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

tms/force-app/main/default/objects/TMS_Ticket__c/fields/TMS_Contact__c.field-meta.xml
<CustomField>
    <fullName>TMS_Contact__c</fullName>
    <label>TMS Contact</label>
    <referenceTo>TMS_Contact__c</referenceTo>
    <relationshipLabel>TMS Tickets</relationshipLabel>
    <relationshipName>TMS_Tickets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

tms/force-app/main/default/classes/tmsContactSearch.cls
public with sharing class tmsContactSearch {
    @AuraEnabled
    public static List<TMS_Contact__c> tmsSearchResult(String firstName, String lastName, String email){
        try {
            String fkey = firstName;
            String lkey =lastName;
            String emailkey =email;
            system.debug([
                SELECT Id, 	First_Name__c,Last_Name__c, Email_Address__c,(SELECT Id, First_Name__c,Last_Name__c,Severity__c FROM TMS_Tickets__r)
                FROM TMS_Contact__c 
                WHERE First_Name__c LIKE :fkey and Last_Name__c LIKE :lkey and Email_Address__c LIKE :emailkey
            ]);
            
            return [
                SELECT Id, 	First_Name__c,Last_Name__c, Email_Address__c,(SELECT Id, First_Name__c,Last_Name__c,Severity__c FROM TMS_Tickets__r)
                FROM TMS_Contact__c 
                WHERE First_Name__c LIKE :fkey and Last_Name__c LIKE :lkey and Email_Address__c LIKE :emailkey
            ];
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}